project_id: '522340'
api_token_env: CROWDIN_PERSONAL_TOKEN
api_token: 948d470179aa13123bbef5a8cb34325b
preserve_hierarchy: true
files:
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
